### PR TITLE
Update applications.md

### PR DESCRIPTION
**Pull request by faboul**
Added two entries which I believe are worth mentioning, namely : Lightning a workbench allowing the specification of domain specific languages in Alloy ( and F-Alloy) and Echo relying on Alloy as a model transformation engine.

### CODE REVIEW

**Comment by pkriens** [comment]
The link does not work. It first redirects to https://www.lightning.gforge.uni.lu which has no valid certificate. Since I am brave, I accepted this and then I got a 404

I do not think we should use a link that has no valid certificate.

**Comment by faboul** [comment]
indeed, the www is too much, thanks for double checking ! :)

**Comment by pkriens** [comment]
I tried to install your plugin in Eclipse but got:

image

**Comment by faboul** [comment]
I can't reproduce this problem on my eclipse oxygen 2, see screenshot below.

screenshot from 2018-06-13 10-54-42

It seems to be a network issue. is your connection going through a proxy or something of the sort ?

**Comment by pkriens** [comment]
My bad, I think there was a space in the pasted url for me. Works.

**Pull request merged**
